INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AF', '', 'Afghanistan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AL', '', 'Albania');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'DZ', '', 'Algeria');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'DS', '', 'American Samoa');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AD', '', 'Andorra');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AO', '', 'Angola');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AI', '', 'Anguilla');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AQ', '', 'Antarctica');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AG', '', 'Antigua and Barbuda');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AR', '', 'Argentina');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AM', '', 'Armenia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AW', '', 'Aruba');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AU', '', 'Australia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AT', '', 'Austria');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AZ', '', 'Azerbaijan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BS', '', 'Bahamas');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BH', '', 'Bahrain');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BD', '', 'Bangladesh');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BB', '', 'Barbados');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BY', '', 'Belarus');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BE', '', 'Belgium');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BZ', '', 'Belize');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BJ', '', 'Benin');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BM', '', 'Bermuda');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BT', '', 'Bhutan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BO', '', 'Bolivia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BA', '', 'Bosnia and Herzegovina');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BW', '', 'Botswana');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BV', '', 'Bouvet Island');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BR', '', 'Brazil');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IO', '', 'British Indian Ocean Territory');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BN', '', 'Brunei Darussalam');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BG', '', 'Bulgaria');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BF', '', 'Burkina Faso');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'BI', '', 'Burundi');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KH', '', 'Cambodia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CM', '', 'Cameroon');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CA', '', 'Canada');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CV', '', 'Cape Verde');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KY', '', 'Cayman Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CF', '', 'Central African Republic');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TD', '', 'Chad');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CL', '', 'Chile');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CN', '', 'China');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CX', '', 'Christmas Island');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CC', '', 'Cocos (Keeling) Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CO', '', 'Colombia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KM', '', 'Comoros');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CD', '', 'Democratic Republic of the Congo');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CG', '', 'Republic of Congo');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CK', '', 'Cook Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CR', '', 'Costa Rica');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'HR', '', 'Croatia (Hrvatska)');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CU', '', 'Cuba');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CY', '', 'Cyprus');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CZ', '', 'Czech Republic');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'DK', '', 'Denmark');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'DJ', '', 'Djibouti');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'DM', '', 'Dominica');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'DO', '', 'Dominican Republic');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TP', '', 'East Timor');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'EC', '', 'Ecuador');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'EG', '', 'Egypt');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SV', '', 'El Salvador');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GQ', '', 'Equatorial Guinea');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ER', '', 'Eritrea');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'EE', '', 'Estonia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ET', '', 'Ethiopia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'FK', '', 'Falkland Islands (Malvinas)');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'FO', '', 'Faroe Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'FJ', '', 'Fiji');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'FI', '', 'Finland');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'FR', '', 'France');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'FX', '', 'France, Metropolitan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GF', '', 'French Guiana');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PF', '', 'French Polynesia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TF', '', 'French Southern Territories');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GA', '', 'Gabon');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GM', '', 'Gambia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GE', '', 'Georgia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'DE', '', 'Germany');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GH', '', 'Ghana');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GI', '', 'Gibraltar');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GK', '', 'Guernsey');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GR', '', 'Greece');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GL', '', 'Greenland');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GD', '', 'Grenada');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GP', '', 'Guadeloupe');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GU', '', 'Guam');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GT', '', 'Guatemala');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GN', '', 'Guinea');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GW', '', 'Guinea-Bissau');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GY', '', 'Guyana');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'HT', '', 'Haiti');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'HM', '', 'Heard and Mc Donald Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'HN', '', 'Honduras');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'HK', '', 'Hong Kong');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'HU', '', 'Hungary');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IS', '', 'Iceland');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IN', '', 'India');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IM', '', 'Isle of Man');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ID', '', 'Indonesia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IR', '', 'Iran (Islamic Republic of)');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IQ', '', 'Iraq');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IE', '', 'Ireland');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IL', '', 'Israel');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'IT', '', 'Italy');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CI', '', 'Ivory Coast');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'JE', '', 'Jersey');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'JM', '', 'Jamaica');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'JP', '', 'Japan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'JO', '', 'Jordan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KZ', '', 'Kazakhstan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KE', '', 'Kenya');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KI', '', 'Kiribati');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KP', '', 'Korea, Democratic People''s Republic of');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KR', '', 'Korea, Republic of');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'XK', '', 'Kosovo');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KW', '', 'Kuwait');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KG', '', 'Kyrgyzstan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LA', '', 'Lao People''s Democratic Republic');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LV', '', 'Latvia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LB', '', 'Lebanon');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LS', '', 'Lesotho');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LR', '', 'Liberia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LY', '', 'Libyan Arab Jamahiriya');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LI', '', 'Liechtenstein');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LT', '', 'Lithuania');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LU', '', 'Luxembourg');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MO', '', 'Macau');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MK', '', 'North Macedonia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MG', '', 'Madagascar');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MW', '', 'Malawi');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MY', '', 'Malaysia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MV', '', 'Maldives');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ML', '', 'Mali');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MT', '', 'Malta');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MH', '', 'Marshall Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MQ', '', 'Martinique');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MR', '', 'Mauritania');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MU', '', 'Mauritius');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TY', '', 'Mayotte');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MX', '', 'Mexico');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'FM', '', 'Micronesia, Federated States of');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MD', '', 'Moldova, Republic of');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MC', '', 'Monaco');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MN', '', 'Mongolia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ME', '', 'Montenegro');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MS', '', 'Montserrat');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MA', '', 'Morocco');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MZ', '', 'Mozambique');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MM', '', 'Myanmar');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NA', '', 'Namibia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NR', '', 'Nauru');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NP', '', 'Nepal');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NL', '', 'Netherlands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AN', '', 'Netherlands Antilles');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NC', '', 'New Caledonia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NZ', '', 'New Zealand');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NI', '', 'Nicaragua');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NE', '', 'Niger');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NG', '', 'Nigeria');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NU', '', 'Niue');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NF', '', 'Norfolk Island');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'MP', '', 'Northern Mariana Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'NO', '', 'Norway');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'OM', '', 'Oman');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PK', '', 'Pakistan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PW', '', 'Palau');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PS', '', 'Palestine');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PA', '', 'Panama');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PG', '', 'Papua New Guinea');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PY', '', 'Paraguay');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PE', '', 'Peru');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PH', '', 'Philippines');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PN', '', 'Pitcairn');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PL', '', 'Poland');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PT', '', 'Portugal');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PR', '', 'Puerto Rico');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'QA', '', 'Qatar');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'RE', '', 'Reunion');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'RO', '', 'Romania');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'RU', '', 'Russian Federation');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'RW', '', 'Rwanda');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'KN', '', 'Saint Kitts and Nevis');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LC', '', 'Saint Lucia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'VC', '', 'Saint Vincent and the Grenadines');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'WS', '', 'Samoa');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SM', '', 'San Marino');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ST', '', 'Sao Tome and Principe');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SA', '', 'Saudi Arabia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SN', '', 'Senegal');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'RS', '', 'Serbia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SC', '', 'Seychelles');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SL', '', 'Sierra Leone');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SG', '', 'Singapore');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SK', '', 'Slovakia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SI', '', 'Slovenia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SB', '', 'Solomon Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SO', '', 'Somalia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ZA', '', 'South Africa');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GS', '', 'South Georgia South Sandwich Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SS', '', 'South Sudan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ES', '', 'Spain');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'LK', '', 'Sri Lanka');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SH', '', 'St. Helena');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'PM', '', 'St. Pierre and Miquelon');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SD', '', 'Sudan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SR', '', 'Suriname');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SJ', '', 'Svalbard and Jan Mayen Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SZ', '', 'Swaziland');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SE', '', 'Sweden');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'CH', '', 'Switzerland');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'SY', '', 'Syrian Arab Republic');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TW', '', 'Taiwan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TJ', '', 'Tajikistan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TZ', '', 'Tanzania, United Republic of');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TH', '', 'Thailand');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TG', '', 'Togo');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TK', '', 'Tokelau');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TO', '', 'Tonga');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TT', '', 'Trinidad and Tobago');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TN', '', 'Tunisia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TR', '', 'Turkey');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TM', '', 'Turkmenistan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TC', '', 'Turks and Caicos Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'TV', '', 'Tuvalu');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'UG', '', 'Uganda');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'UA', '', 'Ukraine');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'AE', '', 'United Arab Emirates');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'GB', '', 'United Kingdom');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'US', '', 'United States');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'UM', '', 'United States minor outlying islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'UY', '', 'Uruguay');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'UZ', '', 'Uzbekistan');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'VU', '', 'Vanuatu');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'VA', '', 'Vatican City State');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'VE', '', 'Venezuela');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'VN', '', 'Vietnam');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'VG', '', 'Virgin Islands (British)');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'VI', '', 'Virgin Islands (U.S.)');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'WF', '', 'Wallis and Futuna Islands');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'EH', '', 'Western Sahara');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'YE', '', 'Yemen');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ZM', '', 'Zambia');
INSERT INTO `tb_item`(`item_tabl`,`item_item`,`short_desc`,`long_desc`) VALUES ('TV406', 'ZW', '', 'Zimbabwe');